apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: test-github-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-github-quarkus 
  name: test-github-quarkus
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: test-github-quarkus 
